name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME}} # User of the server you want to ssh into

          script: |
            mkdir test_javi 
            cd /var/www/ahierro.es
            mkdir testing
            git clone https://github.com/Jacanroman/testing.git
            echo 'Deployment successful to digital ocean' 


# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#- uses: actions/checkout@v3

 # git clone git@github.com:Jacanroman/testing.git


